# Generated from EOIR's public court/hearing roster.
# Source: https://www.justice.gov/eoir/find-immigration-court-and-access-internet-based-hearings

SEEDED_COURTS = [
    {"name": "Adelanto Immigration Court", "address_line1": "Adelanto ICE Processing Center", "address_line2": "10250 Rancho Road, Suite 201A", "city": "Adelanto", "state": "CA", "postal_code": "92301"},
    {"name": "Annandale Immigration Court", "address_line1": "7619 Little River Turnpike, Suite 400", "address_line2": "", "city": "Annandale", "state": "VA", "postal_code": "22003"},
    {"name": "Atlanta - Ted Turner Drive Immigration Court", "address_line1": "180 Ted Turner Drive, SW, Suite 241", "address_line2": "", "city": "Atlanta", "state": "GA", "postal_code": "30303"},
    {"name": "Atlanta - W. Peachtree Street Immigration Court", "address_line1": "Atlanta - W. Peachtree Street", "address_line2": "Peachtree Summit Federal Building, 401 W. Peachtree Street, Suite 2600", "city": "Atlanta", "state": "GA", "postal_code": "30308"},
    {"name": "Aurora Immigration Court", "address_line1": "3130 North Oakland Street", "address_line2": "", "city": "Aurora", "state": "CO", "postal_code": "80010"},
    {"name": "Baltimore Immigration Court", "address_line1": "George Fallon Federal Building", "address_line2": "31 Hopkins Plaza, Rm. 440", "city": "Baltimore", "state": "MD", "postal_code": "21201"},
    {"name": "Batavia Immigration Court", "address_line1": "4250 Federal Drive, Room F108", "address_line2": "", "city": "Batavia", "state": "NY", "postal_code": "14020"},
    {"name": "Boston Immigration Court", "address_line1": "JFK Federal Building", "address_line2": "15 New Sudbury Street, Room 320", "city": "Boston", "state": "MA", "postal_code": "02203"},
    {"name": "Buffalo Immigration Court", "address_line1": "Buffalo Immigration Court", "address_line2": "130 Delaware Avenue, Suite 300", "city": "Buffalo", "state": "NY", "postal_code": "14202"},
    {"name": "Charlotte Immigration Court", "address_line1": "Charlotte Immigration Court", "address_line2": "5701 Executive Center Drive, Suite 400", "city": "Charlotte", "state": "NC", "postal_code": "28212"},
    {"name": "Chelmsford Immigration Court", "address_line1": "150 Apollo Drive, Suite 100", "address_line2": "", "city": "Chelmsford", "state": "MA", "postal_code": "01824"},
    {"name": "Chicago Immigration Court", "address_line1": "55 E. Monroe St., Suite 1500", "address_line2": "", "city": "Chicago", "state": "IL", "postal_code": "60603"},
    {"name": "Cleveland Immigration Court", "address_line1": "801 W. Superior Avenue, Suite 13 - 100", "address_line2": "", "city": "Cleveland", "state": "OH", "postal_code": "44113"},
    {"name": "Concord Immigration Court", "address_line1": "1855 Gateway Boulevard, Suite 850", "address_line2": "", "city": "Concord", "state": "CA", "postal_code": "94520"},
    {"name": "Conroe Immigration Court", "address_line1": "Conroe Immigration Court", "address_line2": "806 Hilbig Road, Suite 2-300, 2nd Floor", "city": "Conroe", "state": "TX", "postal_code": "77301"},
    {"name": "Dallas Immigration Court", "address_line1": "1100 Commerce Street, Suite 1060", "address_line2": "", "city": "Dallas", "state": "TX", "postal_code": "75242"},
    {"name": "Denver Immigration Court", "address_line1": "1961 Stout Street, Suite 3101", "address_line2": "", "city": "Denver", "state": "CO", "postal_code": "80294"},
    {"name": "Detroit Immigration Court", "address_line1": "477 Michigan Avenue, Suite 440", "address_line2": "", "city": "Detroit", "state": "MI", "postal_code": "48226"},
    {"name": "El Paso Immigration Court", "address_line1": "700 E. San Antonio Avenue, Suite 750", "address_line2": "", "city": "El Paso", "state": "TX", "postal_code": "79901"},
    {"name": "El Paso SPC Immigration Court", "address_line1": "8915 Montana Avenue, Suite 100", "address_line2": "", "city": "El Paso", "state": "TX", "postal_code": "79925"},
    {"name": "Elizabeth Immigration Court", "address_line1": "625 Evans Street, Room 148A", "address_line2": "", "city": "Elizabeth", "state": "NJ", "postal_code": "07201"},
    {"name": "Eloy Immigration Court", "address_line1": "1705 E. Hanna Road, Suite 366", "address_line2": "", "city": "Eloy", "state": "AZ", "postal_code": "85131"},
    {"name": "Falls Church IAC Immigration Court", "address_line1": "", "address_line2": "", "city": "", "state": "", "postal_code": ""},
    {"name": "Florence Immigration Court", "address_line1": "3260 N. Pinal Parkway Avenue", "address_line2": "", "city": "Florence", "state": "AZ", "postal_code": "85132"},
    {"name": "Fort Snelling Immigration Court", "address_line1": "Bishop Henry Whipple Federal Building", "address_line2": "1 Federal Drive, Suite 1850", "city": "Fort Snelling", "state": "MN", "postal_code": "55111"},
    {"name": "Fort Worth IAC Immigration Court", "address_line1": "", "address_line2": "", "city": "", "state": "", "postal_code": ""},
    {"name": "Guaynabo Immigration Court", "address_line1": "San Patricio Office Center", "address_line2": "#7 Tabonuco Street, Room 401", "city": "Guaynabo", "state": "PR", "postal_code": "00968-4605"},
    {"name": "Harlingen Immigration Court", "address_line1": "2009 West Jefferson Avenue, Suite 300", "address_line2": "", "city": "Harlingen", "state": "TX", "postal_code": "78550"},
    {"name": "Hartford Immigration Court", "address_line1": "AA Ribicoff Federal Building & Courthouse", "address_line2": "450 Main Street, Suite 628", "city": "Hartford", "state": "CT", "postal_code": "06103-3015"},
    {"name": "Honolulu Immigration Court", "address_line1": "PJKK Federal Building", "address_line2": "300 Ala Moana Blvd., Rm. 8-112", "city": "Honolulu", "state": "HI", "postal_code": "96850"},
    {"name": "Houston - Greenspoint Park Immigration Court", "address_line1": "16800 Greenspoint Park Drive, 2nd Floor", "address_line2": "", "city": "Houston", "state": "TX", "postal_code": "77060"},
    {"name": "Houston - Jefferson Street Immigration Court", "address_line1": "Houston - Jefferson Street Immigration Court", "address_line2": "500 Jefferson Street, Suite 300", "city": "Houston", "state": "TX", "postal_code": "77002"},
    {"name": "Houston - S. Gessner Road Immigration Court", "address_line1": "8701 S. Gessner Road, 10th Floor", "address_line2": "", "city": "Houston", "state": "TX", "postal_code": "77074"},
    {"name": "Hyattsville Immigration Court", "address_line1": "3311 Toledo Road, Suite 105", "address_line2": "", "city": "Hyattsville", "state": "MD", "postal_code": "20782"},
    {"name": "Imperial Immigration Court", "address_line1": "2409 La Brucherie Road", "address_line2": "", "city": "Imperial", "state": "CA", "postal_code": "92251"},
    {"name": "Indianapolis Immigration Court", "address_line1": "Minton-Capehart Federal Building", "address_line2": "575 N. Pennsylvania Street, Suite 617", "city": "Indianapolis", "state": "IN", "postal_code": "46204"},
    {"name": "Kansas City Immigration Court", "address_line1": "2345 Grand Boulevard, Suite 525", "address_line2": "", "city": "Kansas City", "state": "MO", "postal_code": "64108"},
    {"name": "Laredo Immigration Court", "address_line1": "1406 Jacaman Road, Suite B", "address_line2": "", "city": "Laredo", "state": "TX", "postal_code": "78041"},
    {"name": "Las Vegas Immigration Court", "address_line1": "110 North City Parkway, Suite 400", "address_line2": "", "city": "Las Vegas", "state": "NV", "postal_code": "89106"},
    {"name": "LaSalle Immigration Court", "address_line1": "", "address_line2": "", "city": "", "state": "", "postal_code": ""},
    {"name": "Los Angeles - N. Los Angeles Street Immigration Court", "address_line1": "300 North Los Angeles Street, Room 4330", "address_line2": "", "city": "Los Angeles", "state": "CA", "postal_code": "90012"},
    {"name": "Los Angeles - Van Nuys Boulevard Immigration Court", "address_line1": "6230 Van Nuys Blvd. 3rd Floor, Suite 300", "address_line2": "", "city": "Van Nuys", "state": "CA", "postal_code": "91401"},
    {"name": "Los Angeles - West Los Angeles Immigration Court", "address_line1": "", "address_line2": "", "city": "", "state": "", "postal_code": ""},
    {"name": "Memphis Immigration Court", "address_line1": "80 Monroe Avenue, Lower Level Suite G-10", "address_line2": "", "city": "Memphis", "state": "TN", "postal_code": "38103"},
    {"name": "Miami Immigration Court", "address_line1": "One Riverview Square", "address_line2": "333 S. Miami Avenue, Suite 700", "city": "Miami", "state": "FL", "postal_code": "33130"},
    {"name": "Miami Krome (Detained) Immigration Court", "address_line1": "Krome North Processing Center", "address_line2": "18201 SW 12th Street", "city": "Miami", "state": "FL", "postal_code": "33194"},
    {"name": "New Orleans Immigration Court", "address_line1": "One Canal Place", "address_line2": "365 Canal Street, Suite 500", "city": "New Orleans", "state": "LA", "postal_code": "70130"},
    {"name": "New York - Broadway Immigration Court", "address_line1": "Ted Weiss Federal Building", "address_line2": "290 Broadway, 15th Floor", "city": "New York", "state": "NY", "postal_code": "10007"},
    {"name": "New York - Federal Plaza Immigration Court", "address_line1": "26 Federal Plaza, 12th Floor, Room 1237", "address_line2": "", "city": "New York", "state": "NY", "postal_code": "10278"},
    {"name": "New York - Varick Immigration Court", "address_line1": "201 Varick Street, 5th Floor Room 507", "address_line2": "", "city": "New York", "state": "NY", "postal_code": "10014"},
    {"name": "Newark Immigration Court", "address_line1": "970 Broad Street, Room 1200", "address_line2": "", "city": "Newark", "state": "NJ", "postal_code": "07102"},
    {"name": "Oakdale Immigration Court", "address_line1": "1900 E. Whatley Road", "address_line2": "", "city": "Oakdale", "state": "LA", "postal_code": "71463"},
    {"name": "Omaha Immigration Court", "address_line1": "1717 Avenue H, Suite 100", "address_line2": "", "city": "Omaha", "state": "NE", "postal_code": "68110"},
    {"name": "Orlando Immigration Court", "address_line1": "500 N. Orange Ave, Suite 1100", "address_line2": "", "city": "Orlando", "state": "FL", "postal_code": "32801"},
    {"name": "Otay Mesa Immigration Court", "address_line1": "7488 Calzada de la Fuente", "address_line2": "", "city": "San Diego", "state": "CA", "postal_code": "92154"},
    {"name": "Otero Immigration Court", "address_line1": "26 McGregor Range Road, Door #1", "address_line2": "", "city": "Chaparral", "state": "NM", "postal_code": "88081"},
    {"name": "Pearsall Immigration Court", "address_line1": "566 Veterans Drive", "address_line2": "", "city": "Pearsall", "state": "TX", "postal_code": "78061"},
    {"name": "Philadelphia Immigration Court", "address_line1": "Robert Nix Federal Bldg and Courthouse", "address_line2": "900 Market Street, Suite 504", "city": "Philadelphia", "state": "PA", "postal_code": "19107"},
    {"name": "Phoenix Immigration Court", "address_line1": "250 N. Seventh Ave., Suite 300", "address_line2": "", "city": "Phoenix", "state": "AZ", "postal_code": "85007"},
    {"name": "Port Isabel Immigration Court", "address_line1": "27991 Buena Vista Blvd.", "address_line2": "", "city": "Los Fresnos", "state": "TX", "postal_code": "78566"},
    {"name": "Portland Immigration Court", "address_line1": "1220 SW 3rd Avenue, Suite 500", "address_line2": "", "city": "Portland", "state": "OR", "postal_code": "97204"},
    {"name": "Richmond IAC Immigration Court", "address_line1": "", "address_line2": "", "city": "", "state": "", "postal_code": ""},
    {"name": "Sacramento Immigration Court", "address_line1": "John Moss Federal Building", "address_line2": "650 Capitol Mall, Suite 4-200", "city": "Sacramento", "state": "CA", "postal_code": "95814"},
    {"name": "Saipan Immigration Court", "address_line1": "Marina Heights II Building", "address_line2": "Suite 301, Marina Heights Business Park", "city": "Saipan", "state": "MP", "postal_code": "96950"},
    {"name": "Salt Lake City Immigration Court", "address_line1": "2975 South Decker Lake Drive, #200", "address_line2": "", "city": "West Valley City", "state": "UT", "postal_code": "84119-6094"},
    {"name": "San Antonio Immigration Court", "address_line1": "800 Dolorosa, Suite 300", "address_line2": "", "city": "San Antonio", "state": "TX", "postal_code": "78207"},
    {"name": "San Diego Immigration Court", "address_line1": "880 Front Street, Suite 4240", "address_line2": "", "city": "San Diego", "state": "CA", "postal_code": "92101"},
    {"name": "San Francisco Immigration Court", "address_line1": "", "address_line2": "", "city": "", "state": "", "postal_code": ""},
    {"name": "Santa Ana Immigration Court", "address_line1": "1241 E. Dyer Road, Suite 200", "address_line2": "", "city": "Santa Ana", "state": "CA", "postal_code": "92705"},
    {"name": "Seattle Immigration Court", "address_line1": "Seattle Immigration Court", "address_line2": "915 2nd Ave., Suite 613", "city": "Seattle", "state": "WA", "postal_code": "98174"},
    {"name": "Sterling Immigration Court", "address_line1": "Sterling Immigration Court", "address_line2": "21400 Ridgetop Circle, Suite 200", "city": "Sterling", "state": "VA", "postal_code": "20166"},
    {"name": "Stewart Immigration Court", "address_line1": "146 CCA Road", "address_line2": "PO Box 248", "city": "Lumpkin", "state": "GA", "postal_code": "31815"},
    {"name": "Tacoma Immigration Court", "address_line1": "1623 East J Street, Suite 3", "address_line2": "", "city": "Tacoma", "state": "WA", "postal_code": "98421"},
    {"name": "Tucson Immigration Court", "address_line1": "300 West Congress Street, Suite 300", "address_line2": "", "city": "Tucson", "state": "AZ", "postal_code": "85701"},
    {"name": "Ulster Immigration Court", "address_line1": "750 Berme Road, PO Box 800", "address_line2": "", "city": "Napanoch", "state": "NY", "postal_code": "12458"},
]

SEEDED_JUDGES = [
    {"name": "Abby A. Batko-Taylor", "court_name": "Falls Church IAC Immigration Court"},
    {"name": "Abby Meyer", "court_name": "Omaha Immigration Court"},
    {"name": "Abdias Tida", "court_name": "Houston - Jefferson Street Immigration Court"},
    {"name": "Abraham Burgess", "court_name": "Miami Immigration Court"},
    {"name": "Adam Jovanovic", "court_name": "Houston - Greenspoint Park Immigration Court"},
    {"name": "Adam Jovanovic", "court_name": "Houston - S. Gessner Road Immigration Court"},
    {"name": "Adam Panopoulos", "court_name": "Elizabeth Immigration Court"},
    {"name": "Adam Perl", "court_name": "New York - Broadway Immigration Court"},
    {"name": "Adam Rodriguez", "court_name": "Harlingen Immigration Court"},
    {"name": "Aggie Norregard", "court_name": "Santa Ana Immigration Court"},
    {"name": "Akash B. Vyas", "court_name": "Chicago Immigration Court"},
    {"name": "Alec Niziolek", "court_name": "Orlando Immigration Court"},
    {"name": "Alex G. Mason", "court_name": "Houston - Greenspoint Park Immigration Court"},
    {"name": "Alex Perez", "court_name": "Houston - Greenspoint Park Immigration Court"},
    {"name": "Alexander Lee", "court_name": "Houston - Greenspoint Park Immigration Court"},
    {"name": "Alexandra Larsen", "court_name": "Omaha Immigration Court"},
    {"name": "Alice Hartye", "court_name": "Baltimore Immigration Court"},
    {"name": "Alicia Brooks", "court_name": "Charlotte Immigration Court"},
    {"name": "Alisha Campos", "court_name": "Memphis Immigration Court"},
    {"name": "Alison Igoe", "court_name": "Hyattsville Immigration Court"},
    {"name": "Alison Kane", "court_name": "Denver Immigration Court"},
    {"name": "Allan John-Baptiste", "court_name": "Fort Worth IAC Immigration Court"},
    {"name": "Alysha Welsh", "court_name": "Annandale Immigration Court"},
    {"name": "Amanda Jeannopoulos", "court_name": "New York - Federal Plaza Immigration Court"},
    {"name": "Amelia Anderson", "court_name": "San Diego Immigration Court"},
    {"name": "Amit Chugh", "court_name": "Los Angeles - West Los Angeles Immigration Court"},
    {"name": "Amy F. Haer", "court_name": "Atlanta - W. Peachtree Street Immigration Court"},
    {"name": "Amy Lee", "court_name": "Charlotte Immigration Court"},
    {"name": "Ana L. Quiros", "court_name": "Hyattsville Immigration Court"},
    {"name": "Ana Mencini", "court_name": "Chicago Immigration Court"},
    {"name": "Andrea Cole", "court_name": "Conroe Immigration Court"},
    {"name": "Andrea Hong", "court_name": "Los Angeles - N. Los Angeles Street Immigration Court"},
    {"name": "Andrea Siebert", "court_name": "Los Angeles - N. Los Angeles Street Immigration Court"},
    {"name": "Andrew Caborn", "court_name": "Conroe Immigration Court"},
    {"name": "Andrew Fishkin", "court_name": "Santa Ana Immigration Court"},
    {"name": "Andrew Galvao", "court_name": "Harlingen Immigration Court"},
    {"name": "Andrew Hewitt", "court_name": "Atlanta - Ted Turner Drive Immigration Court"},
    {"name": "Andrew J. Slitt", "court_name": "Hartford Immigration Court"},
    {"name": "Andrew M. Calvelli", "court_name": "New York - Broadway Immigration Court"},
    {"name": "Andrew X. Stawar", "court_name": "Houston - S. Gessner Road Immigration Court"},
    {"name": "Angela Munson", "court_name": "Hartford Immigration Court"},
    {"name": "Angela Munson", "court_name": "Boston Immigration Court"},
    {"name": "Angela Munson", "court_name": "Chelmsford Immigration Court"},
    {"name": "Anibal Martinez", "court_name": "San Antonio Immigration Court"},
    {"name": "Anita McFadden", "court_name": "Santa Ana Immigration Court"},
    {"name": "Anita Simons", "court_name": "Los Angeles - West Los Angeles Immigration Court"},
    {"name": "Ann M. McDermott", "court_name": "Las Vegas Immigration Court"},
    {"name": "Anna Adams", "court_name": "Orlando Immigration Court"},
    {"name": "Anna C. Little", "court_name": "New York - Federal Plaza Immigration Court"},
    {"name": "Anna Diao", "court_name": "New York - Broadway Immigration Court"},
    {"name": "Anne Kristina Perry", "court_name": "Imperial Immigration Court"},
    {"name": "Anthony J. Hurst", "court_name": "Cleveland Immigration Court"},
    {"name": "Anthony Maingot", "court_name": "Miami Immigration Court"},
    {"name": "Antonio Capistrano", "court_name": "Philadelphia Immigration Court"},
    {"name": "Anupriya Krishna", "court_name": "Sterling Immigration Court"},
    {"name": "Anwer Khan", "court_name": "Houston - Jefferson Street Immigration Court"},
    {"name": "Arkesia Jenkins-Dargan", "court_name": "Houston - S. Gessner Road Immigration Court"},
    {"name": "Arlene E. Dorfman", "court_name": "Los Angeles - Van Nuys Boulevard Immigration Court"},
    {"name": "Artie Pobjecky", "court_name": "Houston - Greenspoint Park Immigration Court"},
    {"name": "Arya Ranasinghe", "court_name": "New York - Broadway Immigration Court"},
    {"name": "Attila Bogdan", "court_name": "Dallas Immigration Court"},
    {"name": "Audra Behne", "court_name": "Los Angeles - West Los Angeles Immigration Court"},
    {"name": "Audrey Carr", "court_name": "Fort Snelling Immigration Court"},
    {"name": "Aviva Poczter", "court_name": "New York - Broadway Immigration Court"},
    {"name": "Ayodele A. Gansallo", "court_name": "Orlando Immigration Court"},
    {"name": "Ayodele A. Gansallo", "court_name": "Philadelphia Immigration Court"},
    {"name": "Bao Nguyen", "court_name": "Houston - Jefferson Street Immigration Court"},
    {"name": "Barbara A. Nelson", "court_name": "New York - Federal Plaza Immigration Court"},
    {"name": "Barbara Corkery", "court_name": "Sterling Immigration Court"},
    {"name": "Benjamin D. Rosen", "court_name": "Orlando Immigration Court"},
    {"name": "Benjamin D. Williams", "court_name": "Omaha Immigration Court"},
    {"name": "Benjamin S. Kuipers", "court_name": "Phoenix Immigration Court"},
    {"name": "Benjamin Sky Brown", "court_name": "Houston - Greenspoint Park Immigration Court"},
    {"name": "Bianca Brown", "court_name": "Stewart Immigration Court"},
    {"name": "Billy Sapp", "court_name": "Conroe Immigration Court"},
    {"name": "Blake Doughty", "court_name": "Atlanta - W. Peachtree Street Immigration Court"},
    {"name": "Bobbie C. Masters", "court_name": "Aurora Immigration Court"},
    {"name": "Brandi M. Lohr", "court_name": "Buffalo Immigration Court"},
    {"name": "Brandon Alexander “Alex” Kennedy", "court_name": "Cleveland Immigration Court"},
    {"name": "Brandon Hart", "court_name": "Fort Worth IAC Immigration Court"},
    {"name": "Brandon Josephsen", "court_name": "Memphis Immigration Court"},
    {"name": "Brandon Lee Lettunich", "court_name": "El Paso Immigration Court"},
    {"name": "Brea Burgie", "court_name": "Denver Immigration Court"},
    {"name": "Brenda O’Malley", "court_name": "Boston Immigration Court"},
    {"name": "Brendan Curran", "court_name": "Chicago Immigration Court"},
    {"name": "Brent Jostad", "court_name": "Richmond IAC Immigration Court"},
    {"name": "Brent Landis", "court_name": "Houston - Greenspoint Park Immigration Court"},
    {"name": "Brett Parchert", "court_name": "Seattle Immigration Court"},
    {"name": "Brian Burke", "court_name": "Orlando Immigration Court"},
    {"name": "Brian Counihan", "court_name": "Batavia Immigration Court"},
    {"name": "Brian Palmer", "court_name": "Richmond IAC Immigration Court"},
    {"name": "Brian Sardelli", "court_name": "Fort Snelling Immigration Court"},
    {"name": "Brock Taylor", "court_name": "Salt Lake City Immigration Court"},
    {"name": "Bruce Imbacuan", "court_name": "Cleveland Immigration Court"},
    {"name": "Bruce Taylor", "court_name": "Florence Immigration Court"},
    {"name": "Bryan DePowell", "court_name": "Adelanto Immigration Court"},
    {"name": "C. Morgan Kim", "court_name": "Miami Immigration Court"},
    {"name": "Carlos Juelle", "court_name": "Los Angeles - West Los Angeles Immigration Court"},
    {"name": "Carol A. Crawford", "court_name": "New York - Federal Plaza Immigration Court"},
    {"name": "Carol Moore", "court_name": "Newark Immigration Court"},
    {"name": "Carolyn L. Krasinski", "court_name": "New York - Broadway Immigration Court"},
    {"name": "Carrie Johnson-Papillo", "court_name": "New York - Federal Plaza Immigration Court"},
    {"name": "Catherine G. Phillips", "court_name": "New Orleans Immigration Court"},
    {"name": "Catherine Halliday-Roberts", "court_name": "Otay Mesa Immigration Court"},
    {"name": "Catherine Halliday-Roberts", "court_name": "San Diego Immigration Court"},
    {"name": "Cathy Sagesse", "court_name": "New York - Federal Plaza Immigration Court"},
    {"name": "Chad Dotson", "court_name": "Richmond IAC Immigration Court"},
    {"name": "Charles Dishman", "court_name": "Fort Worth IAC Immigration Court"},
    {"name": "Charles Floyd", "court_name": "Tacoma Immigration Court"},
    {"name": "Charles M. Ouslander", "court_name": "Ulster Immigration Court"},
    {"name": "Charles McCullough", "court_name": "San Antonio Immigration Court"},
    {"name": "Charles Purnell", "court_name": "Richmond IAC Immigration Court"},
    {"name": "Charles R. Conroy", "court_name": "New York - Varick Immigration Court"},
    {"name": "Charlotte Marquez", "court_name": "New Orleans Immigration Court"},
    {"name": "Chase Calder Cleveland", "court_name": "Sterling Immigration Court"},
    {"name": "Chevone Sanon", "court_name": "New York - Broadway Immigration Court"},
    {"name": "Chris Brisack", "court_name": "Conroe Immigration Court"},
    {"name": "Christina Martyak", "court_name": "Miami Krome (Detained) Immigration Court"},
    {"name": "Christine Lluis Reis", "court_name": "Miami Immigration Court"},
    {"name": "Christine Olson", "court_name": "Chelmsford Immigration Court"},
    {"name": "Christine Stancill", "court_name": "Los Angeles - West Los Angeles Immigration Court"},
    {"name": "Christopher Cooper", "court_name": "Detroit Immigration Court"},
    {"name": "Christopher Cusmano", "court_name": "New York - Federal Plaza Immigration Court"},
    {"name": "Christopher Greer", "court_name": "Salt Lake City Immigration Court"},
    {"name": "Christopher Phan", "court_name": "Houston - Greenspoint Park Immigration Court"},
    {"name": "​​Christopher Pineda", "court_name": "Harlingen Immigration Court"},
    {"name": "Christopher Schumann", "court_name": "Houston - S. Gessner Road Immigration Court"},
    {"name": "Christopher Thielemann", "court_name": "Dallas Immigration Court"},
    {"name": "CIJ Teresa L. Riley", "court_name": "Cleveland Immigration Court"},
    {"name": "Clarence Wagner", "court_name": "Honolulu Immigration Court"},
    {"name": "Clarence Wagner", "court_name": "Saipan Immigration Court"},
    {"name": "Colin Johnson", "court_name": "Kansas City Immigration Court"},
    {"name": "Corey A. Combs", "court_name": "Newark Immigration Court"},
    {"name": "Courtney Stevens", "court_name": "Laredo Immigration Court"},
    {"name": "Craig DeFoe", "court_name": "Chicago Immigration Court"},
    {"name": "Curtis Pierce", "court_name": "Los Angeles - West Los Angeles Immigration Court"},
    {"name": "Curtis White", "court_name": "Adelanto Immigration Court"},
    {"name": "Cynthia Goodman", "court_name": "Fort Worth IAC Immigration Court"},
    {"name": "Cynthia LaFuente", "court_name": "San Antonio Immigration Court"},
    {"name": "Cynthia Torg", "court_name": "Annandale Immigration Court"},
    {"name": "D'Anna H. Freeman", "court_name": "Fort Worth IAC Immigration Court"},
    {"name": "Dalin Holyoak", "court_name": "Miami Immigration Court"},
    {"name": "Dania Nassar", "court_name": "New York - Federal Plaza Immigration Court"},
    {"name": "Daniel A. Morris", "court_name": "Hartford Immigration Court"},
    {"name": "Daniel Conklin", "court_name": "Indianapolis Immigration Court"},
    {"name": "Daniel Dowell", "court_name": "Miami Immigration Court"},
    {"name": "Daniel J. Daugherty", "court_name": "Las Vegas Immigration Court"},
    {"name": "Daniel J. Gallegos", "court_name": "El Paso Immigration Court"},
    {"name": "Daniel Malvin", "court_name": "Los Angeles - West Los Angeles Immigration Court"},
    {"name": "Daniel P. Kinnicutt", "court_name": "Conroe Immigration Court"},
    {"name": "Daniel P. Kinnicutt", "court_name": "Houston - Jefferson Street Immigration Court"},
    {"name": "Daniel Santander", "court_name": "San Antonio Immigration Court"},
    {"name": "Danielle Garten", "court_name": "Houston - Greenspoint Park Immigration Court"},
    {"name": "Danny Razo", "court_name": "El Paso Immigration Court"},
    {"name": "Dara F. Reid", "court_name": "New York - Varick Immigration Court"},
    {"name": "Darin W. Flagg", "court_name": "Santa Ana Immigration Court"},
    {"name": "Dat T. Vo", "court_name": "Houston - S. Gessner Road Immigration Court"},
    {"name": "David Anderson", "court_name": "Salt Lake City Immigration Court"},
    {"name": "David Evans", "court_name": "Seattle Immigration Court"},
    {"name": "David G. Beyleryan", "court_name": "Dallas Immigration Court"},
    {"name": "David Gardey", "court_name": "Annandale Immigration Court"},
    {"name": "David Green", "court_name": "Fort Worth IAC Immigration Court"},
    {"name": "David Jones", "court_name": "Hyattsville Immigration Court"},
    {"name": "David M. Paxton", "court_name": "Houston - S. Gessner Road Immigration Court"},
    {"name": "David Paruch", "court_name": "Detroit Immigration Court"},
    {"name": "David Russo", "court_name": "Memphis Immigration Court"},
    {"name": "David Whipple", "court_name": "Cleveland Immigration Court"},
    {"name": "David White", "court_name": "Falls Church IAC Immigration Court"},
    {"name": "Dawn Kulick", "court_name": "Philadelphia Immigration Court"},
    {"name": "Dean Tuckman", "court_name": "El Paso SPC Immigration Court"},
    {"name": "Deborah E. Klahr", "court_name": "New York - Federal Plaza Immigration Court"},
    {"name": "Deepali Nadkarni", "court_name": "Annandale Immigration Court"},
    {"name": "Deitrich Sims", "court_name": "Dallas Immigration Court"},
    {"name": "DeLana Jones", "court_name": "Houston - S. Gessner Road Immigration Court"},
    {"name": "Delia I Gonzalez", "court_name": "Harlingen Immigration Court"},
    {"name": "Denise Marks Lane", "court_name": "Miami Immigration Court"},
    {"name": "Dennis Ryan", "court_name": "Newark Immigration Court"},
    {"name": "Diana L. Callaghan", "court_name": "Los Angeles - West Los Angeles Immigration Court"},
    {"name": "Diane L. Dodd", "court_name": "New York - Broadway Immigration Court"},
    {"name": "Dillon J. Ambrose", "court_name": "Chicago Immigration Court"},
    {"name": "Dimple Gupta", "court_name": "Annandale Immigration Court"},
    {"name": "Dinesh Verma", "court_name": "Hyattsville Immigration Court"},
    {"name": "Donald Eller", "court_name": "Fort Worth IAC Immigration Court"},
    {"name": "Donald Pashayan", "court_name": "Cleveland Immigration Court"},
    {"name": "Dorothy Harbeck", "court_name": "New York - Federal Plaza Immigration Court"},
    {"name": "Drew T. Nishiyama", "court_name": "Seattle Immigration Court"},
    {"name": "Elisa M. Sukkar", "court_name": "Miami Immigration Court"},
    {"name": "Elisa M. Sukkar", "court_name": "Guaynabo Immigration Court"},
    {"name": "Elisa M. Sukkar (EMS )", "court_name": "Miami Krome (Detained) Immigration Court"},
    {"name": "Elizabeth Cottor", "court_name": "Phoenix Immigration Court"},
    {"name": "Elizabeth Crites", "court_name": "Chicago Immigration Court"},
    {"name": "Elizabeth Kessler", "court_name": "Hyattsville Immigration Court"},
    {"name": "Elizabeth Lang", "court_name": "Orlando Immigration Court"},
    {"name": "Elizabeth Martinez", "court_name": "San Antonio Immigration Court"},
    {"name": "Elizabeth Treacy", "court_name": "Chicago Immigration Court"},
    {"name": "Ellen Karesh", "court_name": "Richmond IAC Immigration Court"},
    {"name": "Elvin Talavera-Peraza", "court_name": "Orlando Immigration Court"},
    {"name": "Elvin Talavera-Peraza", "court_name": "Guaynabo Immigration Court"},
    {"name": "Emily Farrar-Crockett", "court_name": "Annandale Immigration Court"},
    {"name": "Emmanuel Garcia", "court_name": "Laredo Immigration Court"},
    {"name": "Eric Levinson", "court_name": "Charlotte Immigration Court"},
    {"name": "Eric Marsteller", "court_name": "New Orleans Immigration Court"},
    {"name": "Eric Schultz", "court_name": "Buffalo Immigration Court"},
    {"name": "Eric Stransky", "court_name": "Omaha Immigration Court"},
    {"name": "Eric Tijerina", "court_name": "San Antonio Immigration Court"},
    {"name": "Eugene Robinson", "court_name": "Otay Mesa Immigration Court"},
    {"name": "Eva Saltzman", "court_name": "Chicago Immigration Court"},
    {"name": "F. James Loprest Jr.", "court_name": "New York - Federal Plaza Immigration Court"},
    {"name": "Fayaz Habib", "court_name": "New York - Broadway Immigration Court"},
    {"name": "Ferdinand Lugo Ortiz", "court_name": "Tacoma Immigration Court"},
    {"name": "Forrest Hoover", "court_name": "Philadelphia Immigration Court"},
    {"name": "Francis Mwangi", "court_name": "Fort Worth IAC Immigration Court"},
    {"name": "Francisco Mendez", "court_name": "Annandale Immigration Court"},
    {"name": "Francisco R. Prieto", "court_name": "New York - Varick Immigration Court"},
    {"name": "Frank Pimentel", "court_name": "Port Isabel Immigration Court"},
    {"name": "Frank Seminerio", "court_name": "San Francisco Immigration Court"},
    {"name": "Gabriel Bradley", "court_name": "Los Angeles - West Los Angeles Immigration Court"},
    {"name": "Gary Endelman", "court_name": "Houston - Jefferson Street Immigration Court"},
    {"name": "Gary L. Bergosh", "court_name": "New Orleans Immigration Court"},
    {"name": "Geoffrey Hoffman", "court_name": "Houston - S. Gessner Road Immigration Court"},
    {"name": "George Ward", "court_name": "Falls Church IAC Immigration Court"},
    {"name": "Ghunise L. Coaxum", "court_name": "Atlanta - W. Peachtree Street Immigration Court"},
    {"name": "Gilda Terrazas", "court_name": "Tucson Immigration Court"},
    {"name": "Gina Reynolds", "court_name": "Chicago Immigration Court"},
    {"name": "Gioia Maiellano", "court_name": "New York - Federal Plaza Immigration Court"},
    {"name": "Gordan S. Vincent", "court_name": "Baltimore Immigration Court"},
    {"name": "Gregory Simmons", "court_name": "Santa Ana Immigration Court"},
    {"name": "Gurney F. Pearsall III", "court_name": "Hyattsville Immigration Court"},
    {"name": "Guy Grande", "court_name": "San Diego Immigration Court"},
    {"name": "Hayden Windrow", "court_name": "Seattle Immigration Court"},
    {"name": "Heather Libeu", "court_name": "Santa Ana Immigration Court"},
    {"name": "Holly D'Andrea", "court_name": "Conroe Immigration Court"},
    {"name": "Howard Hom", "court_name": "Santa Ana Immigration Court"},
    {"name": "Hugo Martinez", "court_name": "Fort Worth IAC Immigration Court"},
    {"name": "Huy Le", "court_name": "Chelmsford Immigration Court"},
    {"name": "Hye Chon", "court_name": "Los Angeles - Van Nuys Boulevard Immigration Court"},
    {"name": "Ian Simons", "court_name": "Detroit Immigration Court"},
    {"name": "IJ Philip P. Taylor", "court_name": "Atlanta - W. Peachtree Street Immigration Court"},
    {"name": "Illya-Karina Bonet", "court_name": "Sterling Immigration Court"},
    {"name": "Iman Ghasri", "court_name": "Santa Ana Immigration Court"},
    {"name": "Irene C. Feldman", "court_name": "Eloy Immigration Court"},
    {"name": "Irene C. Feldman", "court_name": "Florence Immigration Court"},
    {"name": "Irene C. Feldman", "court_name": "Phoenix Immigration Court"},
    {"name": "Irene C. Feldman", "court_name": "Tucson Immigration Court"},
    {"name": "Irene Recio", "court_name": "Miami Immigration Court"},
    {"name": "Irma Diaz​", "court_name": "Hyattsville Immigration Court"},
    {"name": "Irma Newburn", "court_name": "Memphis Immigration Court"},
    {"name": "Ivan Gardzelewski", "court_name": "Denver Immigration Court"},
    {"name": "J. Thomas Bartleson", "court_name": "New York - Broadway Immigration Court"},
    {"name": "Jacinto Palomino", "court_name": "Otero Immigration Court"},
    {"name": "Jack D. Patten III", "court_name": "Denver Immigration Court"},
    {"name": "Jacob Bashore", "court_name": "Fort Worth IAC Immigration Court"},
    {"name": "Jacob J. Stender", "court_name": "Concord Immigration Court"},
    {"name": "Jacob Marshall", "court_name": "Chicago Immigration Court"},
    {"name": "Jacob T. Addicott", "court_name": "New York - Broadway Immigration Court"},
    {"name": "Jacob Weintraub", "court_name": "New York - Broadway Immigration Court"},
    {"name": "Jacquelyn Jo. Joyce", "court_name": "Houston - S. Gessner Road Immigration Court"},
    {"name": "Jaime Jasso", "court_name": "Los Angeles - N. Los Angeles Street Immigration Court"},
    {"name": "James A. Klinedinst", "court_name": "Orlando Immigration Court"},
    {"name": "James Crofts", "court_name": "Atlanta - Ted Turner Drive Immigration Court"},
    {"name": "James Dehn", "court_name": "Sterling Immigration Court"},
    {"name": "James F. Polivka", "court_name": "Fort Worth IAC Immigration Court"},
    {"name": "James Graulich", "court_name": "Richmond IAC Immigration Court"},
    {"name": "James Holden", "court_name": "Indianapolis Immigration Court"},
    {"name": "James M. McCarthy", "court_name": "New York - Broadway Immigration Court"},
    {"name": "James Miller Jr.", "court_name": "El Paso Immigration Court"},
    {"name": "James Nugent", "court_name": "Dallas Immigration Court"},
    {"name": "James R. McKee", "court_name": "New York - Broadway Immigration Court"},
    {"name": "Jane Miller", "court_name": "Indianapolis Immigration Court"},
    {"name": "Janette Allen", "court_name": "El Paso Immigration Court"},
    {"name": "Jankana Desai", "court_name": "Los Angeles - West Los Angeles Immigration Court"},
    {"name": "Jared Grimmer", "court_name": "Kansas City Immigration Court"},
    {"name": "Jared M. Kennedy", "court_name": "Conroe Immigration Court"},
    {"name": "Jared Robinson", "court_name": "Houston - S. Gessner Road Immigration Court"},
    {"name": "Jason Braun", "court_name": "Annandale Immigration Court"},
    {"name": "Jason Hermus", "court_name": "Dallas Immigration Court"},
    {"name": "Jason L. Stern", "court_name": "Houston - Greenspoint Park Immigration Court"},
    {"name": "Jason Pope", "court_name": "Sterling Immigration Court"},
    {"name": "Jason Thomas", "court_name": "Chelmsford Immigration Court"},
    {"name": "Jason Waterloo", "court_name": "Santa Ana Immigration Court"},
    {"name": "Jason Waterloo", "court_name": "Honolulu Immigration Court"},
    {"name": "Jason Waterloo", "court_name": "Saipan Immigration Court"},
    {"name": "Javier Balasquide", "court_name": "Miami Immigration Court"},
    {"name": "Jayme Salinardi", "court_name": "Kansas City Immigration Court"},
    {"name": "Jayme Salinardi", "court_name": "Omaha Immigration Court"},
    {"name": "Jayme Salinardi", "court_name": "Pearsall Immigration Court"},
    {"name": "Jayme Salinardi", "court_name": "San Antonio Immigration Court"},
    {"name": "Jeannette Park", "court_name": "Los Angeles - Van Nuys Boulevard Immigration Court"},
    {"name": "Jeffery Nance", "court_name": "Charlotte Immigration Court"},
    {"name": "Jeffrey Frederick", "court_name": "Orlando Immigration Court"},
    {"name": "Jeffrey Munoz", "court_name": "Imperial Immigration Court"},
    {"name": "Jeffrey Sprague", "court_name": "Baltimore Immigration Court"},
    {"name": "Jeffry S. Brady", "court_name": "Orlando Immigration Court"},
    {"name": "Jem Sponzo", "court_name": "New York - Federal Plaza Immigration Court"},
    {"name": "Jennifer C. Whitko", "court_name": "Denver Immigration Court"},
    {"name": "Jennifer Chung", "court_name": "New York - Broadway Immigration Court"},
    {"name": "Jennifer Gaz", "court_name": "Phoenix Immigration Court"},
    {"name": "Jennifer L. Mazza", "court_name": "Pearsall Immigration Court"},
    {"name": "Jennifer May", "court_name": "Fort Worth IAC Immigration Court"},
    {"name": "Jennifer Page-Lozano", "court_name": "Orlando Immigration Court"},
    {"name": "Jennifer Piateski", "court_name": "Richmond IAC Immigration Court"},
    {"name": "Jennifer R. Bell", "court_name": "Atlanta - W. Peachtree Street Immigration Court"},
    {"name": "Jennifer Riedthaler-Williams", "court_name": "Cleveland Immigration Court"},
    {"name": "Jennifer Winfield", "court_name": "Dallas Immigration Court"},
    {"name": "Jeremy Santoro", "court_name": "Cleveland Immigration Court"},
    {"name": "Jeremy Sibert", "court_name": "Denver Immigration Court"},
    {"name": "Jerrica Harness", "court_name": "Stewart Immigration Court"},
    {"name": "Jessica Miles", "court_name": "El Paso SPC Immigration Court"},
    {"name": "Jesus J. Ybarra", "court_name": "Laredo Immigration Court"},
    {"name": "Jill K. Krishnan", "court_name": "Detroit Immigration Court"},
    {"name": "John A. Poore", "court_name": "Dallas Immigration Court"},
    {"name": "John C. Barnes", "court_name": "Fort Worth IAC Immigration Court"},
    {"name": "John Carle", "court_name": "Philadelphia Immigration Court"},
    {"name": "John Cortes", "court_name": "Phoenix Immigration Court"},
    {"name": "John DeCure", "court_name": "New York - Varick Immigration Court"},
    {"name": "John Furlong Jr.", "court_name": "Boston Immigration Court"},
    {"name": "John J. Siemietkowski", "court_name": "New York - Federal Plaza Immigration Court"},
    {"name": "John McPhail", "court_name": "Conroe Immigration Court"},
    {"name": "John Odell", "court_name": "Tacoma Immigration Court"},
    {"name": "John P. Burns", "court_name": "New York - Federal Plaza Immigration Court"},
    {"name": "John P. Burns", "court_name": "Ulster Immigration Court"},
    {"name": "John P. Fucetola", "court_name": "Sterling Immigration Court"},
    {"name": "John Rubenstein", "court_name": "Hyattsville Immigration Court"},
    {"name": "John T. Driscoll", "court_name": "Los Angeles - West Los Angeles Immigration Court"},
    {"name": "Jon P. Calandruccio", "court_name": "New Orleans Immigration Court"},
    {"name": "Jonathan Andresen", "court_name": "Houston - S. Gessner Road Immigration Court"},
    {"name": "Jonathan Huang", "court_name": "Santa Ana Immigration Court"},
    {"name": "Jonathan M. Brent", "court_name": "Los Angeles - Van Nuys Boulevard Immigration Court"},
    {"name": "Jonathan Owens", "court_name": "Detroit Immigration Court"},
    {"name": "Jonathan Owens", "court_name": "Cleveland Immigration Court"},
    {"name": "Jonathan Reingold", "court_name": "New York - Federal Plaza Immigration Court"},
    {"name": "Jonathan W. Hitesman", "court_name": "Adelanto Immigration Court"},
    {"name": "Jonathan W. Hitesman", "court_name": "Sacramento Immigration Court"},
    {"name": "Jonathan W. Hitesman", "court_name": "Las Vegas Immigration Court"},
    {"name": "Jorene Soto", "court_name": "Annandale Immigration Court"},
    {"name": "Jorge Pereira", "court_name": "Miami Krome (Detained) Immigration Court"},
    {"name": "Jose Penalosa", "court_name": "San Diego Immigration Court"},
    {"name": "Jose Rivera-Ortiz", "court_name": "Miami Immigration Court"},
    {"name": "Joseph Kassell", "court_name": "Richmond IAC Immigration Court"},
    {"name": "Joseph LaRocca", "court_name": "New Orleans Immigration Court"},
    {"name": "Joseph Leonard", "court_name": "Harlingen Immigration Court"},
    {"name": "Joseph Q. Andelin", "court_name": "Salt Lake City Immigration Court"},
    {"name": "Joseph Scott", "court_name": "Philadelphia Immigration Court"},
    {"name": "Joseph Weiner", "court_name": "Los Angeles - Van Nuys Boulevard Immigration Court"},
    {"name": "Joshua D. Quidley", "court_name": "Baltimore Immigration Court"},
    {"name": "Joshua D. Rosen", "court_name": "Tacoma Immigration Court"},
    {"name": "Joshua Luskin", "court_name": "Chicago Immigration Court"},
    {"name": "Joshua Osborn", "court_name": "Houston - Greenspoint Park Immigration Court"},
    {"name": "Joy Lampley-Fortson", "court_name": "Atlanta - Ted Turner Drive Immigration Court"},
    {"name": "Joy Lampley-Fortson", "court_name": "Atlanta - W. Peachtree Street Immigration Court"},
    {"name": "Joy Lampley-Fortson", "court_name": "Stewart Immigration Court"},
    {"name": "Joyce Bakke Varzandeh", "court_name": "Los Angeles - West Los Angeles Immigration Court"},
    {"name": "Joyce Noche", "court_name": "Santa Ana Immigration Court"},
    {"name": "Juan Román", "court_name": "Omaha Immigration Court"},
    {"name": "Judith Bonilla", "court_name": "El Paso Immigration Court"},
    {"name": "Julia Diaz-Rex", "court_name": "Orlando Immigration Court"},
    {"name": "Julia Diaz-Rex", "court_name": "Guaynabo Immigration Court"},
    {"name": "Julia Egy", "court_name": "Sterling Immigration Court"},
    {"name": "Julian Castaneda", "court_name": "Harlingen Immigration Court"},
    {"name": "Julie Adams", "court_name": "Baltimore Immigration Court"},
    {"name": "Julie Nelson", "court_name": "Concord Immigration Court"},
    {"name": "Julie Nelson", "court_name": "San Francisco Immigration Court"},
    {"name": "June Lee", "court_name": "Hyattsville Immigration Court"},
    {"name": "Justin Adams", "court_name": "San Antonio Immigration Court"},
    {"name": "Justin Bennett", "court_name": "Hartford Immigration Court"},
    {"name": "Justin Dinsdale", "court_name": "Houston - Greenspoint Park Immigration Court"},
    {"name": "Justin Howard", "court_name": "Kansas City Immigration Court"},
    {"name": "Justin M. Price", "court_name": "Concord Immigration Court"},
    {"name": "Kalenna Lee", "court_name": "New York - Broadway Immigration Court"},
    {"name": "Kalin Ivany", "court_name": "Fort Snelling Immigration Court"},
    {"name": "Kandra Robbins", "court_name": "LaSalle Immigration Court"},
    {"name": "Karen Donoso Stevens", "court_name": "Annandale Immigration Court"},
    {"name": "Karen Nazaire", "court_name": "Newark Immigration Court"},
    {"name": "Karen Y. Hope", "court_name": "Sterling Immigration Court"},
    {"name": "Karen.Marquez-Casillas", "court_name": "Sterling Immigration Court"},
    {"name": "Katherine Estes", "court_name": "Kansas City Immigration Court"},
    {"name": "Katherine Hansen", "court_name": "Detroit Immigration Court"},
    {"name": "Katherine Hansen", "court_name": "Fort Snelling Immigration Court"},
    {"name": "Kathryn DeAngelis", "court_name": "Tucson Immigration Court"},
    {"name": "Katie Mullins", "court_name": "Adelanto Immigration Court"},
    {"name": "Kelley Sydnor", "court_name": "Atlanta - Ted Turner Drive Immigration Court"},
    {"name": "Kelly Lake", "court_name": "Memphis Immigration Court"},
    {"name": "Kenneth Shahan", "court_name": "Fort Worth IAC Immigration Court"},
    {"name": "Kenneth Sogabe", "court_name": "Seattle Immigration Court"},
    {"name": "Kenya Wells", "court_name": "Houston - Greenspoint Park Immigration Court"},
    {"name": "Kevin Brown", "court_name": "Houston - S. Gessner Road Immigration Court"},
    {"name": "Kevin D. Stroberg", "court_name": "Atlanta - W. Peachtree Street Immigration Court"},
    {"name": "Kevin Gross", "court_name": "Dallas Immigration Court"},
    {"name": "Kevin N. Buras", "court_name": "Houston - Jefferson Street Immigration Court"},
    {"name": "Kevin Riley", "court_name": "Los Angeles - N. Los Angeles Street Immigration Court"},
    {"name": "Kevin Riley", "court_name": "Los Angeles - Van Nuys Boulevard Immigration Court"},
    {"name": "Kevin Stanley", "court_name": "Orlando Immigration Court"},
    {"name": "Kevin Terrill", "court_name": "Pearsall Immigration Court"},
    {"name": "Khalilah Taylor", "court_name": "New York - Broadway Immigration Court"},
    {"name": "Khalilah Taylor", "court_name": "New York - Varick Immigration Court"},
    {"name": "Kiera Parikh", "court_name": "Houston - Jefferson Street Immigration Court"},
    {"name": "Kieran M. Lalor", "court_name": "Ulster Immigration Court"},
    {"name": "Kristie Anne Padron", "court_name": "Sterling Immigration Court"},
    {"name": "Kristin Piepmeier", "court_name": "Santa Ana Immigration Court"},
    {"name": "Kristopher McDonald", "court_name": "Los Angeles - West Los Angeles Immigration Court"},
    {"name": "Kuyomars Golparvar", "court_name": "Baltimore Immigration Court"},
    {"name": "Kuyomars Golparvar", "court_name": "Hyattsville Immigration Court"},
    {"name": "Kyle A. Dandelet", "court_name": "New York - Federal Plaza Immigration Court"},
    {"name": "Kyle Mitchell", "court_name": "Dallas Immigration Court"},
    {"name": "Kyle Myers", "court_name": "El Paso Immigration Court"},
    {"name": "Kyle Pearson", "court_name": "Atlanta - Ted Turner Drive Immigration Court"},
    {"name": "Kyung Auh", "court_name": "Ulster Immigration Court"},
    {"name": "Lakshmi Herman", "court_name": "Miami Immigration Court"},
    {"name": "Laura Figueroa", "court_name": "Laredo Immigration Court"},
    {"name": "Laura Wyrosdick", "court_name": "Sterling Immigration Court"},
    {"name": "Lauren F. Farber", "court_name": "Philadelphia Immigration Court"},
    {"name": "Leah A. O'Brien", "court_name": "San Diego Immigration Court"},
    {"name": "Leila Mullican", "court_name": "Newark Immigration Court"},
    {"name": "Lena Golovnin", "court_name": "New York - Federal Plaza Immigration Court"},
    {"name": "Lenka J. Koss", "court_name": "Annandale Immigration Court"},
    {"name": "Leo Finston", "court_name": "Newark Immigration Court"},
    {"name": "Leon Francis", "court_name": "Santa Ana Immigration Court"},
    {"name": "Lian Yeh", "court_name": "Houston - S. Gessner Road Immigration Court"},
    {"name": "Lily Hsu", "court_name": "Santa Ana Immigration Court"},
    {"name": "Linda Hristova", "court_name": "New York - Federal Plaza Immigration Court"},
    {"name": "Linda L. Chavez", "court_name": "Pearsall Immigration Court"},
    {"name": "Lindsay W. Pepi", "court_name": "San Diego Immigration Court"},
    {"name": "Lindsy R. Roberts", "court_name": "Las Vegas Immigration Court"},
    {"name": "Lionel Martin", "court_name": "Houston - S. Gessner Road Immigration Court"},
    {"name": "Lisa de Cardona", "court_name": "Falls Church IAC Immigration Court"},
    {"name": "Lisa W. Ling", "court_name": "New York - Varick Immigration Court"},
    {"name": "Liviu Lungu", "court_name": "Miami Krome (Detained) Immigration Court"},
    {"name": "Lolita Lukose", "court_name": "Annandale Immigration Court"},
    {"name": "Lorely Fernandez", "court_name": "El Paso Immigration Court"},
    {"name": "Lorianne M. Campanella", "court_name": "Annandale Immigration Court"},
    {"name": "Lory G. Brown", "court_name": "Baltimore Immigration Court"},
    {"name": "Lourdes Martinez-Esquivel", "court_name": "Miami Immigration Court"},
    {"name": "Lourdes Rodriguez de Jongh", "court_name": "Miami Immigration Court"},
    {"name": "Luciana Dubuc", "court_name": "Chelmsford Immigration Court"},
    {"name": "Lucky Narain", "court_name": "New York - Federal Plaza Immigration Court"},
    {"name": "Lucy Baez", "court_name": "New York - Federal Plaza Immigration Court"},
    {"name": "Luisa Santiago", "court_name": "Richmond IAC Immigration Court"},
    {"name": "Luther Snavely", "court_name": "Sterling Immigration Court"},
    {"name": "Lydia Tamez", "court_name": "Houston - Greenspoint Park Immigration Court"},
    {"name": "Lynn Wang", "court_name": "Houston - Jefferson Street Immigration Court"},
    {"name": "Madeline Garcia", "court_name": "Miami Immigration Court"},
    {"name": "Maithe Gonzalez", "court_name": "LaSalle Immigration Court"},
    {"name": "Marc Stahl", "court_name": "Chicago Immigration Court"},
    {"name": "Margaret Burkhart", "court_name": "San Antonio Immigration Court"},
    {"name": "Margaret Kolbe", "court_name": "New York - Varick Immigration Court"},
    {"name": "Margaret R. MacGregor", "court_name": "Port Isabel Immigration Court"},
    {"name": "Maria Akalski", "court_name": "New York - Varick Immigration Court"},
    {"name": "Maria Jaimes-Salgado", "court_name": "Houston - Greenspoint Park Immigration Court"},
    {"name": "Maria T. Ubarri", "court_name": "Miami Immigration Court"},
    {"name": "Mario Sturla", "court_name": "Boston Immigration Court"},
    {"name": "Maritza Ramos", "court_name": "Houston - Jefferson Street Immigration Court"},
    {"name": "Mark Carter", "court_name": "New Orleans Immigration Court"},
    {"name": "Mark Jebson", "court_name": "Detroit Immigration Court"},
    {"name": "Mark K. Brooks", "court_name": "Hyattsville Immigration Court"},
    {"name": "Mark Sameit", "court_name": "Otay Mesa Immigration Court"},
    {"name": "Marlem Nava", "court_name": "Concord Immigration Court"},
    {"name": "Marni Guerrero", "court_name": "Phoenix Immigration Court"},
    {"name": "Marsha Nettles", "court_name": "Miami Immigration Court"},
    {"name": "Martinque Parker", "court_name": "Houston - Greenspoint Park Immigration Court"},
    {"name": "Mary C. Baumgarten", "court_name": "Buffalo Immigration Court"},
    {"name": "Mary Futcher", "court_name": "Philadelphia Immigration Court"},
    {"name": "Mary Lee", "court_name": "Philadelphia Immigration Court"},
    {"name": "Matthew A. Kozyra", "court_name": "Orlando Immigration Court"},
    {"name": "Matthew A. McLeod", "court_name": "Memphis Immigration Court"},
    {"name": "Matthew Andrasko", "court_name": "Portland Immigration Court"},
    {"name": "Matthew C. Beese", "court_name": "Chicago Immigration Court"},
    {"name": "Matthew Chan", "court_name": "Los Angeles - N. Los Angeles Street Immigration Court"},
    {"name": "Matthew E. Sweet", "court_name": "Annandale Immigration Court"},
    {"name": "Matthew Gordon", "court_name": "Sterling Immigration Court"},
    {"name": "Matthew Morrissey", "court_name": "Omaha Immigration Court"},
    {"name": "Matthew S. Johnson", "court_name": "Annandale Immigration Court"},
    {"name": "Matthew W. Kaufman", "court_name": "Aurora Immigration Court"},
    {"name": "Matthew W. Kaufman", "court_name": "Denver Immigration Court"},
    {"name": "Meghan C. Buhl-Madsen", "court_name": "Aurora Immigration Court"},
    {"name": "Melanie Corrin", "court_name": "Denver Immigration Court"},
    {"name": "Melissa Fox", "court_name": "Philadelphia Immigration Court"},
    {"name": "Melissa Joy Garcia", "court_name": "Harlingen Immigration Court"},
    {"name": "Melissa Joy Garcia", "court_name": "Laredo Immigration Court"},
    {"name": "Melissa Joy Garcia", "court_name": "Port Isabel Immigration Court"},
    {"name": "Melissa Karlen", "court_name": "Phoenix Immigration Court"},
    {"name": "Melissa L. Isaak", "court_name": "Atlanta - W. Peachtree Street Immigration Court"},
    {"name": "Meredith Tyrakoski", "court_name": "San Antonio Immigration Court"},
    {"name": "Michael C. Engel", "court_name": "Hyattsville Immigration Court"},
    {"name": "Michael G. McFarland", "court_name": "New York - Federal Plaza Immigration Court"},
    {"name": "Michael Hayden", "court_name": "Charlotte Immigration Court"},
    {"name": "Michael Hussey", "court_name": "Hyattsville Immigration Court"},
    {"name": "Michael Klosowsky", "court_name": "Chicago Immigration Court"},
    {"name": "Michael Lewis", "court_name": "Annandale Immigration Court"},
    {"name": "Michael Neal", "court_name": "Newark Immigration Court"},
    {"name": "Michael Paul Taylor", "court_name": "Baltimore Immigration Court"},
    {"name": "Michael Pleters", "court_name": "El Paso SPC Immigration Court"},
    {"name": "Michael Schnitzer", "court_name": "Eloy Immigration Court"},
    {"name": "Michael Tisocco", "court_name": "Seattle Immigration Court"},
    {"name": "Michael Tripi", "court_name": "Cleveland Immigration Court"},
    {"name": "Michael W. Lloyd", "court_name": "Tucson Immigration Court"},
    {"name": "Michael Walleisa", "court_name": "Miami Immigration Court"},
    {"name": "Michelle Araneta", "court_name": "Miami Immigration Court"},
    {"name": "Michelle Kahan", "court_name": "Boston Immigration Court"},
    {"name": "Michelle Lakomy", "court_name": "Annandale Immigration Court"},
    {"name": "Michelle Slayton", "court_name": "Portland Immigration Court"},
    {"name": "Michelle Venci", "court_name": "Chicago Immigration Court"},
    {"name": "Miguel Cordero-Gonzalez", "court_name": "Houston - S. Gessner Road Immigration Court"},
    {"name": "Monica Guidry", "court_name": "Houston - Greenspoint Park Immigration Court"},
    {"name": "Monica Neumann", "court_name": "Miami Immigration Court"},
    {"name": "Monte Horton", "court_name": "Cleveland Immigration Court"},
    {"name": "Monte Miller", "court_name": "Fort Snelling Immigration Court"},
    {"name": "Munish Sharda", "court_name": "Phoenix Immigration Court"},
    {"name": "Nancy Miller", "court_name": "Los Angeles - N. Los Angeles Street Immigration Court"},
    {"name": "Nancy Nevarez-Myrick", "court_name": "Hyattsville Immigration Court"},
    {"name": "Natalie Huddleston", "court_name": "Florence Immigration Court"},
    {"name": "Natalie Smith", "court_name": "Chelmsford Immigration Court"},
    {"name": "Nathan Herbert", "court_name": "Otero Immigration Court"},
    {"name": "Nathan Herbert", "court_name": "El Paso Immigration Court"},
    {"name": "Nathan Herbert (NHB", "court_name": "El Paso SPC Immigration Court"},
    {"name": "Nathan M. Hansen", "court_name": "Fort Snelling Immigration Court"},
    {"name": "Nathaniel B. Walker", "court_name": "Santa Ana Immigration Court"},
    {"name": "Nelson Vargas-Padilla", "court_name": "Baltimore Immigration Court"},
    {"name": "Nicholas B. Lucic", "court_name": "Houston - Jefferson Street Immigration Court"},
    {"name": "Nicholas Martz", "court_name": "Falls Church IAC Immigration Court"},
    {"name": "Nicholle Hempel", "court_name": "Houston - Greenspoint Park Immigration Court"},
    {"name": "Nicolas Orechwa", "court_name": "Eloy Immigration Court"},
    {"name": "Nicole Lane", "court_name": "Newark Immigration Court"},
    {"name": "Nicole Mouakar", "court_name": "Orlando Immigration Court"},
    {"name": "Nimmo Bhagat", "court_name": "Houston - Jefferson Street Immigration Court"},
    {"name": "Nina M. Carbone", "court_name": "Denver Immigration Court"},
    {"name": "Njeri Maldonado", "court_name": "Atlanta - W. Peachtree Street Immigration Court"},
    {"name": "Olga Attia", "court_name": "San Diego Immigration Court"},
    {"name": "Oshea Spencer", "court_name": "Houston - Greenspoint Park Immigration Court"},
    {"name": "Pallavi Shirole", "court_name": "Baltimore Immigration Court"},
    {"name": "Patrick Barrett", "court_name": "Adelanto Immigration Court"},
    {"name": "Patrick Burke", "court_name": "Cleveland Immigration Court"},
    {"name": "Patrick McKenna", "court_name": "Chicago Immigration Court"},
    {"name": "Paul Habich", "court_name": "Phoenix Immigration Court"},
    {"name": "Paul Hable", "court_name": "Port Isabel Immigration Court"},
    {"name": "Paul Medved", "court_name": "Los Angeles - Van Nuys Boulevard Immigration Court"},
    {"name": "Paul N. Jones", "court_name": "Dallas Immigration Court"},
    {"name": "Pedro Espinal", "court_name": "Orlando Immigration Court"},
    {"name": "Pedro Espinal", "court_name": "Guaynabo Immigration Court"},
    {"name": "Peter A. Kim", "court_name": "Chicago Immigration Court"},
    {"name": "Peter T. McCary", "court_name": "Elizabeth Immigration Court"},
    {"name": "Phoebe Riner", "court_name": "Sterling Immigration Court"},
    {"name": "Rachel L. Wilson", "court_name": "Memphis Immigration Court"},
    {"name": "Rachel Ruane", "court_name": "Los Angeles - N. Los Angeles Street Immigration Court"},
    {"name": "Ralph Girvin", "court_name": "Otero Immigration Court"},
    {"name": "Ramin Rastegar", "court_name": "Newark Immigration Court"},
    {"name": "Randall Fluke", "court_name": "Fort Worth IAC Immigration Court"},
    {"name": "Raphael Choi", "court_name": "Annandale Immigration Court"},
    {"name": "Raphael Rojas", "court_name": "Orlando Immigration Court"},
    {"name": "Ravit Halperin", "court_name": "Adelanto Immigration Court"},
    {"name": "Rebecca Niburg", "court_name": "Hyattsville Immigration Court"},
    {"name": "Rene Mateo", "court_name": "Miami Immigration Court"},
    {"name": "Revathi Muneer", "court_name": "Houston - Jefferson Street Immigration Court"},
    {"name": "Richard B. Cato", "court_name": "Orlando Immigration Court"},
    {"name": "Richard Drucker", "court_name": "Cleveland Immigration Court"},
    {"name": "Richard Jacobs", "court_name": "Fort Worth IAC Immigration Court"},
    {"name": "Richard Jamadar", "court_name": "Orlando Immigration Court"},
    {"name": "Richard Ozmun", "court_name": "Dallas Immigration Court"},
    {"name": "Richard Vanveldhuisen", "court_name": "Annandale Immigration Court"},
    {"name": "Rico Sogocio", "court_name": "Miami Immigration Court"},
    {"name": "Rifian Newaz", "court_name": "San Antonio Immigration Court"},
    {"name": "Robert C. O’Neil", "court_name": "Los Angeles - West Los Angeles Immigration Court"},
    {"name": "Robert K. Lundberg", "court_name": "Annandale Immigration Court"},
    {"name": "Robert K. Lundberg", "court_name": "Falls Church IAC Immigration Court"},
    {"name": "Robert K. Lundberg", "court_name": "Sterling Immigration Court"},
    {"name": "Robert L. Gundlach", "court_name": "New York - Broadway Immigration Court"},
    {"name": "Robert L. Martin", "court_name": "Dallas Immigration Court"},
    {"name": "Robert Lewandowski", "court_name": "Falls Church IAC Immigration Court"},
    {"name": "Robert McSeveney", "court_name": "Seattle Immigration Court"},
    {"name": "Robert P. Driscoll", "court_name": "Indianapolis Immigration Court"},
    {"name": "Robert P. Driscoll", "court_name": "Memphis Immigration Court"},
    {"name": "Robert Powell", "court_name": "Conroe Immigration Court"},
    {"name": "Robert R. McKee", "court_name": "Pearsall Immigration Court"},
    {"name": "Roberto Amaya", "court_name": "Los Angeles - Van Nuys Boulevard Immigration Court"},
    {"name": "Robin Donato", "court_name": "Richmond IAC Immigration Court"},
    {"name": "Robin Feder", "court_name": "Honolulu Immigration Court"},
    {"name": "Robyn Ross", "court_name": "Aurora Immigration Court"},
    {"name": "Rodger Harris", "court_name": "Orlando Immigration Court"},
    {"name": "Rodin Rooyani", "court_name": "Los Angeles - West Los Angeles Immigration Court"},
    {"name": "Roel Canales", "court_name": "Laredo Immigration Court"},
    {"name": "Romy Lerner", "court_name": "Miami Krome (Detained) Immigration Court"},
    {"name": "Ryan Fisher", "court_name": "Atlanta - W. Peachtree Street Immigration Court"},
    {"name": "Ryan J. Clark", "court_name": "Portland Immigration Court"},
    {"name": "Ryan Thompson", "court_name": "Memphis Immigration Court"},
    {"name": "Sam Brown", "court_name": "Houston - Jefferson Street Immigration Court"},
    {"name": "Samantha Begovich", "court_name": "San Diego Immigration Court"},
    {"name": "Samia Naseem", "court_name": "Chicago Immigration Court"},
    {"name": "Samuel G. Williams", "court_name": "Otero Immigration Court"},
    {"name": "Samuel M. Factor", "court_name": "New York - Federal Plaza Immigration Court"},
    {"name": "Sandra Santos-Garcia", "court_name": "Los Angeles - Van Nuys Boulevard Immigration Court"},
    {"name": "Sarah B. Yeomans", "court_name": "Sterling Immigration Court"},
    {"name": "Sarah Mazzie", "court_name": "Fort Snelling Immigration Court"},
    {"name": "Saul Greenstein", "court_name": "Houston - Jefferson Street Immigration Court"},
    {"name": "Scott Alexander", "court_name": "Miami Immigration Court"},
    {"name": "Scott Bratton", "court_name": "Indianapolis Immigration Court"},
    {"name": "Scott Criss", "court_name": "Charlotte Immigration Court"},
    {"name": "Scott Ison", "court_name": "Kansas City Immigration Court"},
    {"name": "Scott Simpson", "court_name": "San Diego Immigration Court"},
    {"name": "Scott Thomsen", "court_name": "Indianapolis Immigration Court"},
    {"name": "Scott V. Greenbaum", "court_name": "Houston - Jefferson Street Immigration Court"},
    {"name": "Shadee M. Star", "court_name": "Concord Immigration Court"},
    {"name": "Shana Chen", "court_name": "Newark Immigration Court"},
    {"name": "Shane Johnson", "court_name": "Seattle Immigration Court"},
    {"name": "ShaSha Xu", "court_name": "New York - Broadway Immigration Court"},
    {"name": "Shayne M. Welling", "court_name": "Sterling Immigration Court"},
    {"name": "Shayne R. Burnham", "court_name": "New York - Varick Immigration Court"},
    {"name": "Sheila Gallow", "court_name": "Atlanta - Ted Turner Drive Immigration Court"},
    {"name": "Sherease R. Pratt", "court_name": "Annandale Immigration Court"},
    {"name": "Sherron Ashworth", "court_name": "LaSalle Immigration Court"},
    {"name": "Sherron Ashworth", "court_name": "New Orleans Immigration Court"},
    {"name": "Sherron Ashworth", "court_name": "Oakdale Immigration Court"},
    {"name": "Shirley Lazare-Raphael", "court_name": "New York - Broadway Immigration Court"},
    {"name": "Stephen Mander", "court_name": "Miami Immigration Court"},
    {"name": "Stephen P. Alcorn", "court_name": "Sterling Immigration Court"},
    {"name": "Stephen Ruhle", "court_name": "El Paso SPC Immigration Court"},
    {"name": "Stephen Stewart", "court_name": "Richmond IAC Immigration Court"},
    {"name": "Steve Mannion", "court_name": "Richmond IAC Immigration Court"},
    {"name": "Steven Caley", "court_name": "Portland Immigration Court"},
    {"name": "Steven Fuller", "court_name": "Stewart Immigration Court"},
    {"name": "Steven Kirchner", "court_name": "San Francisco Immigration Court"},
    {"name": "Steven Marcus", "court_name": "Los Angeles - Van Nuys Boulevard Immigration Court"},
    {"name": "Steven Meredith", "court_name": "El Paso Immigration Court"},
    {"name": "Stuart Alcorn", "court_name": "Pearsall Immigration Court"},
    {"name": "Stuart J. Zander", "court_name": "Imperial Immigration Court"},
    {"name": "Stuart Siegel", "court_name": "Miami Krome (Detained) Immigration Court"},
    {"name": "Sujata Rodgers", "court_name": "Chelmsford Immigration Court"},
    {"name": "Susan Phan", "court_name": "Sacramento Immigration Court"},
    {"name": "Susanna Martinez", "court_name": "El Paso Immigration Court"},
    {"name": "Suzette Smikle", "court_name": "Atlanta - W. Peachtree Street Immigration Court"},
    {"name": "Taiyyeba S. Skomra", "court_name": "Los Angeles - N. Los Angeles Street Immigration Court"},
    {"name": "Tamar Wilson", "court_name": "Elizabeth Immigration Court"},
    {"name": "Tammy Fitting", "court_name": "Tacoma Immigration Court"},
    {"name": "Tanawa Lebreton", "court_name": "New York - Broadway Immigration Court"},
    {"name": "Tanisha Bowens-McCatty", "court_name": "Hyattsville Immigration Court"},
    {"name": "Tara Naselow-Nahas", "court_name": "Dallas Immigration Court"},
    {"name": "Tara Naselow-Nahas", "court_name": "Fort Worth IAC Immigration Court"},
    {"name": "Terese Tadros-Ibarra", "court_name": "Santa Ana Immigration Court"},
    {"name": "Thanos Kanellakos", "court_name": "Hyattsville Immigration Court"},
    {"name": "Theresa Holmes-Simmons", "court_name": "Charlotte Immigration Court"},
    {"name": "Theresa Holmes-Simmons", "court_name": "Richmond IAC Immigration Court"},
    {"name": "Theresa Scala", "court_name": "Portland Immigration Court"},
    {"name": "Theresa Scala", "court_name": "Salt Lake City Immigration Court"},
    {"name": "Theresa Scala", "court_name": "Seattle Immigration Court"},
    {"name": "Theresa Scala", "court_name": "Tacoma Immigration Court"},
    {"name": "Thomas Ayze", "court_name": "Miami Immigration Court"},
    {"name": "Thomas C. Allmond", "court_name": "Orlando Immigration Court"},
    {"name": "Thomas Crossan", "court_name": "San Antonio Immigration Court"},
    {"name": "Thomas Johnson", "court_name": "Houston - S. Gessner Road Immigration Court"},
    {"name": "Tiesha Peal", "court_name": "New York - Federal Plaza Immigration Court"},
    {"name": "Timothy Everett", "court_name": "Los Angeles - N. Los Angeles Street Immigration Court"},
    {"name": "Timothy M. Cole", "court_name": "Conroe Immigration Court"},
    {"name": "Todd A. Masters", "court_name": "Boston Immigration Court"},
    {"name": "Traci Winder", "court_name": "Tacoma Immigration Court"},
    {"name": "Tyler Wood", "court_name": "Denver Immigration Court"},
    {"name": "Valerie Burch", "court_name": "Indianapolis Immigration Court"},
    {"name": "Veronica Segovia", "court_name": "Pearsall Immigration Court"},
    {"name": "Veronica Villegas", "court_name": "Los Angeles - West Los Angeles Immigration Court"},
    {"name": "Victoria Levin", "court_name": "Florence Immigration Court"},
    {"name": "Vikram Badrinath", "court_name": "Sacramento Immigration Court"},
    {"name": "Virna Wright", "court_name": "New York - Federal Plaza Immigration Court"},
    {"name": "Wade Napier", "court_name": "Richmond IAC Immigration Court"},
    {"name": "Wilbur Lee", "court_name": "Santa Ana Immigration Court"},
    {"name": "William David Neumeister", "court_name": "Sacramento Immigration Court"},
    {"name": "William H. McDermott", "court_name": "Philadelphia Immigration Court"},
    {"name": "William Mabry III", "court_name": "Eloy Immigration Court"},
    {"name": "Winfield Murray", "court_name": "Atlanta - W. Peachtree Street Immigration Court"},
    {"name": "Xavier Racine", "court_name": "Sterling Immigration Court"},
    {"name": "Xinzhe Zhang", "court_name": "Phoenix Immigration Court"},
    {"name": "Xiomara Davis-Gumbs", "court_name": "Dallas Immigration Court"},
    {"name": "Yeshaya Poyurs", "court_name": "Hyattsville Immigration Court"},
    {"name": "Yon Alberdi", "court_name": "Orlando Immigration Court"},
    {"name": "Yul-mi Cho", "court_name": "Chelmsford Immigration Court"},
    {"name": "Yvan Murad", "court_name": "Los Angeles - West Los Angeles Immigration Court"},
    {"name": "Yvonne Gonzalez", "court_name": "San Antonio Immigration Court"},
    {"name": "Zol Rainey", "court_name": "Richmond IAC Immigration Court"},
]
